name: Run Automation Tests

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Give permissions to gradle
      run: |
        chmod +x gradlew

    - name: Run tests
      run: |
        ./gradlew clean test

    - name: Upload Screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: screenshots
      if: always()
